% Ex. 16

cx(X) --> cccc(X);ccc(X);cc(X);c(X).
c([zero])-->[0].
c([um])-->[1].
c([dois])-->[2].
c([tres])-->[3].
c([quatro])-->[4].
c([cinco])-->[5].
c([seis])-->[6].
c([sete])-->[7].
c([oito])-->[8].
c([nove])-->[9].
cc([dez])-->[1,0].
cc([onze])-->[1,1].
cc([doze])-->[1,2].
cc([treze])-->[1,3].
cc([quatorze])-->[1,4].
cc([quinze])-->[1,5].
cc([dezesseis])-->[1,6].
cc([dezessete])-->[1,7].
cc([dezoito])-->[1,8].
cc([dezenove])-->[1,9].
cc([vinte])-->[2,0].
cc([vinte,e|C])-->[2],c[C].
cc([trinta])-->[3,0].
cc([trinta,e|C])-->[3],c[C].
cc([quarenta])-->[4,0].
cc([quarenta,e|C])-->[4],c[C].
cc([cinquenta])-->[5,0].
cc([cinquenta,e|C])-->[5],c[C].
cc([sessenta])-->[6,0].
cc([sessenta,e|C])-->[6],c[C].
cc([setenta])-->[7,0].
cc([setenta,e|C])-->[7],c[C].
cc([oitenta])-->[8,0].
cc([oitenta,e|C])-->[8],c[C].
cc([noventa])-->[9,0].
cc([noventa,e|C])-->[9],c[C].
ccc([cem])-->[1,0,0].
ccc([cento,e|CC])-->[1],cc(CC).
ccc([duzentos])-->[2,0,0].
ccc([duzentos,e|CC])-->[2],cc(CC).
ccc([trezentos])-->[3,0,0].
ccc([trezentos,e|CC])-->[3],cc(CC).
ccc([quatrocentos])-->[4,0,0].
ccc([quatrocentos,e|CC])-->[4],cc(CC).
ccc([quinhentos])-->[5,0,0].
ccc([quinhentos,e|CC])-->[5],cc(CC).
ccc([seiscentos])-->[6,0,0].
ccc([seiscentos,e|CC])-->[6],cc(CC).
ccc([setecentos])-->[7,0,0].
ccc([setecentos,e|CC])-->[7],cc(CC).
ccc([oitocentos])-->[8,0,0].
ccc([oitocentos,e|CC])-->[8],cc(CC).
ccc([novecentos])-->[9,0,0].
ccc([novecentos,e|CC])-->[9],cc(CC).
cccc([mil])-->[1,0,0,0].